"""create control plane storage

Revision ID: 20260828_0001
Revises:
Create Date: 2026-08-28 21:37:05.216848+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260828_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "decision_retention_days", sa.Integer(), server_default=sa.text("90"), nullable=False
        ),
        sa.Column(
            "audit_retention_days", sa.Integer(), server_default=sa.text("365"), nullable=False
        ),
        sa.Column("legal_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audit_retention_days BETWEEN 1 AND 3650", name=op.f("ck_tenants_audit_retention")
        ),
        sa.CheckConstraint(
            "decision_retention_days BETWEEN 1 AND 3650", name=op.f("ck_tenants_decision_retention")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "agent_risk_rollups",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=256), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("decision_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("high_risk_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision_count >= 0 AND high_risk_count >= 0",
            name=op.f("ck_agent_risk_rollups_counts"),
        ),
        sa.CheckConstraint(
            "risk_score BETWEEN 0 AND 1", name=op.f("ck_agent_risk_rollups_risk_score")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agent_risk_rollups_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_risk_rollups")),
        sa.UniqueConstraint("tenant_id", "agent_id", name="uq_agent_risk_rollup"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_agent_risk_rollups_tenant_id_id"),
    )
    op.create_index(
        "ix_agent_risk_tenant_score",
        "agent_risk_rollups",
        ["tenant_id", "risk_score", "agent_id"],
        unique=False,
    )
    op.create_table(
        "canonical_actions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("input_digest", sa.LargeBinary(), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("redacted_action", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("detail_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "octet_length(input_digest) = 32", name=op.f("ck_canonical_actions_input_digest_length")
        ),
        sa.CheckConstraint(
            "redacted_action IS NOT NULL OR detail_deleted_at IS NOT NULL",
            name=op.f("ck_canonical_actions_retention_tombstone"),
        ),
        sa.CheckConstraint("schema_version > 0", name=op.f("ck_canonical_actions_schema_version")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_canonical_actions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_actions")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_canonical_actions_tenant_id_id"),
    )
    op.create_index(
        "ix_canonical_actions_tenant_created",
        "canonical_actions",
        ["tenant_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_canonical_actions_tenant_digest",
        "canonical_actions",
        ["tenant_id", "input_digest"],
        unique=False,
    )
    op.create_table(
        "dashboard_aggregates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_granularity", sa.String(length=8), nullable=False),
        sa.Column("metric_key", sa.String(length=100), nullable=False),
        sa.Column(
            "dimension_key", sa.String(length=256), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "bucket_granularity IN ('hour', 'day')",
            name=op.f("ck_dashboard_aggregates_bucket_granularity"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_dashboard_aggregates_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_aggregates")),
        sa.UniqueConstraint(
            "tenant_id",
            "bucket_start",
            "bucket_granularity",
            "metric_key",
            "dimension_key",
            name="uq_dashboard_aggregate_bucket",
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_dashboard_aggregates_tenant_id_id"),
    )
    op.create_index(
        "ix_dashboard_aggregates_tenant_metric_bucket",
        "dashboard_aggregates",
        ["tenant_id", "metric_key", "bucket_start"],
        unique=False,
    )
    op.create_table(
        "integration_health",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("integration_key", sa.String(length=128), nullable=False),
        sa.Column("integration_kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("safe_diagnostic_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "status IN ('HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN')",
            name=op.f("ck_integration_health_status"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name=op.f("ck_integration_health_latency")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_integration_health_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_health")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_integration_health_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "integration_key", name="uq_integration_health_key"),
    )
    op.create_index(
        "ix_integration_health_tenant_status",
        "integration_health",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("identity_kind", sa.String(length=16), nullable=False),
        sa.Column("workload_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(identity_kind = 'workload' AND workload_id IS NOT NULL) OR "
            "(identity_kind = 'human' AND workload_id IS NULL)",
            name=op.f("ck_principals_workload_identity_shape"),
        ),
        sa.CheckConstraint(
            "identity_kind IN ('workload', 'human')", name=op.f("ck_principals_identity_kind")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_principals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_principals_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "issuer", "subject", name="uq_principals_tenant_subject"),
    )
    op.create_index(
        "ix_principals_tenant_kind", "principals", ["tenant_id", "identity_kind"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("agent_id", sa.String(length=256), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("behavioral_score", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("blast_radius", sa.String(length=32), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mitre_mappings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("predicted_next", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("policy_decision", sa.String(length=32), nullable=False),
        sa.Column("policy_pack_version", sa.String(length=128), nullable=False),
        sa.Column("evidence_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pipeline_timings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("detail_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "policy_decision IN ('ALLOW', 'DENY', 'REQUIRE_APPROVAL', 'NOT_APPLICABLE')",
            name=op.f("ck_decisions_policy_decision"),
        ),
        sa.CheckConstraint(
            "response_status IN ('PENDING', 'DELIVERY_PENDING', 'DELIVERED', 'FAILED', 'EXECUTED')",
            name=op.f("ck_decisions_response_status"),
        ),
        sa.CheckConstraint(
            "verdict IN ('ALLOW', 'BLOCK', 'WOULD-BLOCK')", name=op.f("ck_decisions_verdict")
        ),
        sa.CheckConstraint(
            "behavioral_score BETWEEN 0 AND 1", name=op.f("ck_decisions_behavioral_score")
        ),
        sa.CheckConstraint(
            "reasons IS NOT NULL OR detail_deleted_at IS NOT NULL",
            name=op.f("ck_decisions_retention_tombstone"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "action_id"],
            ["canonical_actions.tenant_id", "canonical_actions.id"],
            name=op.f("fk_decisions_tenant_id_canonical_actions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_decisions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_decisions_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_decisions_tenant_idempotency"),
        sa.UniqueConstraint("tenant_id", "trace_id", name="uq_decisions_tenant_trace"),
    )
    op.create_index(
        "ix_decisions_tenant_agent_created",
        "decisions",
        ["tenant_id", "agent_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_decisions_tenant_created", "decisions", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "ix_decisions_tenant_verdict_created",
        "decisions",
        ["tenant_id", "verdict", "created_at"],
        unique=False,
    )
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("assigned_by_principal_id", sa.UUID(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('viewer', 'analyst', 'operator', 'auditor', 'administrator')",
            name=op.f("ck_role_assignments_role"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assigned_by_principal_id"],
            ["principals.tenant_id", "principals.id"],
            name="fk_role_assignments_assigned_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "principal_id"],
            ["principals.tenant_id", "principals.id"],
            name="fk_role_assignments_principal",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_role_assignments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_role_assignments_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "principal_id", "role", name="uq_role_assignment"),
    )
    op.create_index(
        "ix_role_assignments_tenant_role", "role_assignments", ["tenant_id", "role"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("principal_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("previous_digest", sa.LargeBinary(), nullable=True),
        sa.Column("digest", sa.LargeBinary(), nullable=False),
        sa.Column("integrity_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitive_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detail_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("octet_length(digest) = 32", name=op.f("ck_audit_events_digest_length")),
        sa.CheckConstraint(
            "previous_digest IS NULL OR octet_length(previous_digest) = 32",
            name=op.f("ck_audit_events_previous_digest_length"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_audit_events_positive_sequence")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "decision_id"],
            ["decisions.tenant_id", "decisions.id"],
            name=op.f("fk_audit_events_tenant_id_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "principal_id"],
            ["principals.tenant_id", "principals.id"],
            name=op.f("fk_audit_events_tenant_id_principals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("tenant_id", "digest", name="uq_audit_events_tenant_digest"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_audit_events_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "sequence", name="uq_audit_events_tenant_sequence"),
    )
    op.create_index(
        "ix_audit_events_tenant_occurred",
        "audit_events",
        ["tenant_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_tenant_type_occurred",
        "audit_events",
        ["tenant_id", "event_type", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "outbox_deliveries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("deduplication_key", sa.String(length=200), nullable=False),
        sa.Column("destination_key", sa.String(length=128), nullable=False),
        sa.Column("delivery_kind", sa.String(length=64), nullable=False),
        sa.Column("redacted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("10"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_http_status", sa.Integer(), nullable=True),
        sa.Column("safe_diagnostic_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'IN_FLIGHT', 'DELIVERED', 'DEAD_LETTER')",
            name=op.f("ck_outbox_deliveries_state"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts > 0", name=op.f("ck_outbox_deliveries_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "decision_id"],
            ["decisions.tenant_id", "decisions.id"],
            name=op.f("fk_outbox_deliveries_tenant_id_decisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_deliveries")),
        sa.UniqueConstraint("tenant_id", "deduplication_key", name="uq_outbox_deduplication"),
        sa.UniqueConstraint("tenant_id", "delivery_id", name="uq_outbox_delivery_id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_outbox_deliveries_tenant_id_id"),
    )
    op.create_index(
        "ix_outbox_tenant_state_next",
        "outbox_deliveries",
        ["tenant_id", "state", "next_attempt_at", "id"],
        unique=False,
    )
    op.create_table(
        "policy_matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.String(length=200), nullable=False),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("effect", sa.String(length=32), nullable=False),
        sa.Column("safe_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "effect IN ('ALLOW', 'DENY', 'REQUIRE_APPROVAL')", name=op.f("ck_policy_matches_effect")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "decision_id"],
            ["decisions.tenant_id", "decisions.id"],
            name=op.f("fk_policy_matches_tenant_id_decisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_matches")),
        sa.UniqueConstraint("tenant_id", "decision_id", "rule_id", name="uq_policy_match_rule"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_policy_matches_tenant_id_id"),
    )
    op.create_index(
        "ix_policy_matches_tenant_decision",
        "policy_matches",
        ["tenant_id", "decision_id"],
        unique=False,
    )
    op.create_index(
        "ix_policy_matches_tenant_rule", "policy_matches", ["tenant_id", "rule_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_policy_matches_tenant_rule", table_name="policy_matches")
    op.drop_index("ix_policy_matches_tenant_decision", table_name="policy_matches")
    op.drop_table("policy_matches")
    op.drop_index("ix_outbox_tenant_state_next", table_name="outbox_deliveries")
    op.drop_table("outbox_deliveries")
    op.drop_index("ix_audit_events_tenant_type_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_tenant_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_role_assignments_tenant_role", table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index("ix_decisions_tenant_verdict_created", table_name="decisions")
    op.drop_index("ix_decisions_tenant_created", table_name="decisions")
    op.drop_index("ix_decisions_tenant_agent_created", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_principals_tenant_kind", table_name="principals")
    op.drop_table("principals")
    op.drop_index("ix_integration_health_tenant_status", table_name="integration_health")
    op.drop_table("integration_health")
    op.drop_index("ix_dashboard_aggregates_tenant_metric_bucket", table_name="dashboard_aggregates")
    op.drop_table("dashboard_aggregates")
    op.drop_index("ix_canonical_actions_tenant_digest", table_name="canonical_actions")
    op.drop_index("ix_canonical_actions_tenant_created", table_name="canonical_actions")
    op.drop_table("canonical_actions")
    op.drop_index("ix_agent_risk_tenant_score", table_name="agent_risk_rollups")
    op.drop_table("agent_risk_rollups")
    op.drop_table("tenants")
    # ### end Alembic commands ###
